# Generated by Django 3.2.19 on 2023-05-20 10:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Название предприятия', max_length=200, verbose_name='Название предприятия')),
            ],
        ),
        migrations.CreateModel(
            name='Division',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Название дивизиона', max_length=200, verbose_name='Название дивизиона')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(help_text='Текст нового вопроса', verbose_name='Текст вопроса')),
                ('pub_date', models.DateTimeField(auto_now_add=True, help_text='Дата и время создания вопроса', verbose_name='Дата и время создания вопроса')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Электронная почта')),
                ('company', models.ForeignKey(help_text='Предприятие направлющее вопрос', on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='form.company', verbose_name='Предприятие')),
            ],
            options={
                'ordering': ('pub_date',),
            },
        ),
        migrations.AddField(
            model_name='company',
            name='division',
            field=models.ForeignKey(help_text='Дивизион, к которому относиться предприятие', on_delete=django.db.models.deletion.PROTECT, related_name='company', to='form.division', verbose_name='Дивизион'),
        ),
    ]
