# Generated by Django 3.2.19 on 2023-05-20 16:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='company',
        ),
        migrations.AddField(
            model_name='company',
            name='questions',
            field=models.ForeignKey(default=1, help_text='Выбирите ваше предприятие', on_delete=django.db.models.deletion.CASCADE, related_name='company', to='form.question', verbose_name='Вопросы'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='company',
            name='division',
            field=models.ForeignKey(help_text='Выберите ваш дивизион', on_delete=django.db.models.deletion.PROTECT, related_name='company', to='form.division', verbose_name='Дивизион'),
        ),
        migrations.AlterField(
            model_name='question',
            name='email',
            field=models.EmailField(blank=True, help_text='Если вы хотите лично получить ответ на ваш вопрос, оставьте электронную почту, на которую необходимо отправить ответ (можно не корпоративную)', max_length=254, null=True, verbose_name='Электронная почта'),
        ),
        migrations.AlterField(
            model_name='question',
            name='text',
            field=models.TextField(help_text='Задайте ваш вопрос генеральному директору Госкорпорации "Росатом" А.Е. Лихачеву', verbose_name='Текст вопроса'),
        ),
    ]
