# Generated by Django 3.2.19 on 2023-05-20 19:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0002_auto_20230520_1611'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='questions',
        ),
        migrations.AddField(
            model_name='question',
            name='company',
            field=models.ForeignKey(default=1, help_text='Выберите вашу компанию', on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='form.company', verbose_name='Предприятие'),
            preserve_default=False,
        ),
    ]
