# Generated by Django 3.2.19 on 2023-05-21 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0003_auto_20230520_1928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='title',
            field=models.CharField(blank=True, help_text='Название предприятия', max_length=200, verbose_name='Название предприятия'),
        ),
    ]
