# Generated by Django 3.2.19 on 2023-05-21 13:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0004_alter_company_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='title',
            field=models.CharField(help_text='Название предприятия', max_length=200, unique=True, verbose_name='Название предприятия'),
        ),
        migrations.AlterField(
            model_name='division',
            name='title',
            field=models.CharField(help_text='Название дивизиона', max_length=200, unique=True, verbose_name='Название дивизиона'),
        ),
        migrations.AlterField(
            model_name='question',
            name='company',
            field=models.ForeignKey(help_text='Выберите вашt предприятие', on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='form.company', verbose_name='Предприятие'),
        ),
    ]
