# Generated by Django 3.2.19 on 2023-05-23 12:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0006_auto_20230522_1908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='division',
            field=models.ForeignKey(help_text='Выберите ваш дивизион', on_delete=django.db.models.deletion.PROTECT, related_name='companies', to='form.division', verbose_name='Дивизион'),
        ),
        migrations.AlterField(
            model_name='question',
            name='email',
            field=models.EmailField(blank=True, help_text='Если вы хотите лично получить ответ на ваш вопрос, оставьте электронную почту, на которую необходимо отправить ответ (можно не корпоративную)', max_length=254, null=True, verbose_name='E-mail'),
        ),
    ]
