# Generated by Django 3.2.19 on 2023-05-24 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0007_auto_20230523_1228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='email',
            field=models.EmailField(blank=True, help_text='E-mail', max_length=254, null=True, verbose_name='E-mail'),
        ),
        migrations.AlterField(
            model_name='question',
            name='text',
            field=models.TextField(help_text='Текст вопроса', verbose_name='Текст вопроса'),
        ),
    ]
